# Sign up endpoint
POST http://localhost:3030/signup
Content-Type: application/json

{
  "userName": "student-1",
  "password": "123",
  "phone": "+8801540179777",
  "email": "sunny.cse7575@gmail.com"
}

###
# SignIn endpoint
POST http://localhost:3030/signin
Content-Type: application/json

{
  "userName": "admin",
  "password": "itiswhatitis"
}

> {% client.global.set("PRAROMVIK", response.body.json.token); %}


###
POST http://localhost:3030/user/upload
Content-Type: multipart/form-data

{
'image=@"/home/anisur/Downloads/100daysleetcode.png"'
}
